/**
 * CropSmart Mock Data & Database
 */

const cropDatabase = [
    {
        name: "Rice",
        localName: "Chawal",
        image_emoji: "🌾",
        suitableSeasons: ["Kharif"],
        suitableSoils: ["Alluvial", "Clay", "Loamy"],
        phRange: [5.0, 7.0],
        tempRange: [20, 35],
        rainfallRange: [1000, 2500],
        irrigation: ["Rainfed", "Canal", "Tank"],
        nitrogen: ["Medium", "High"],
        phosphorus: ["Medium"],
        potassium: ["Medium", "High"],
        budget: ["Medium", "High"],
        cropType: "Cereal",
        states: ["Maharashtra", "Punjab", "UP", "Karnataka", "Tamil Nadu", "AP", "Bihar"],
        avgYield: "2.5 tonnes/acre",
        avgRevenue: 14000,
        riskLevel: "Low",
        waterRequirement: "High",
        growthDuration: "90–120 days",
        marketDemand: "High",
        mspSupport: true,
        pros: ["High demand", "MSP support", "Good for food security"],
        cons: ["High water requirement", "Labour intensive"],
        tips: "Transplant seedlings 25–30 days after sowing. Maintain 5cm water level."
    },
    {
        name: "Wheat",
        localName: "Gehu",
        image_emoji: "🍞",
        suitableSeasons: ["Rabi"],
        suitableSoils: ["Alluvial", "Clay", "Loamy"],
        phRange: [6.0, 7.5],
        tempRange: [10, 25],
        rainfallRange: [400, 800],
        irrigation: ["Canal", "Borewell"],
        nitrogen: ["High"],
        phosphorus: ["Medium"],
        potassium: ["Medium"],
        budget: ["Medium"],
        cropType: "Cereal",
        states: ["Punjab", "Haryana", "UP", "MP", "Rajasthan", "Bihar"],
        avgYield: "1.8 tonnes/acre",
        avgRevenue: 12500,
        riskLevel: "Low",
        waterRequirement: "Medium",
        growthDuration: "120–150 days",
        marketDemand: "High",
        mspSupport: true,
        pros: ["Stable market", "High nutritional value", "Less water than rice"],
        cons: ["Sensitive to heat waves", "Requires timely sowing"],
        tips: "Sow between Oct 25 and Nov 15. Ensure 4–6 irrigations at critical stages."
    },
    {
        name: "Maize",
        localName: "Makka",
        image_emoji: "🌽",
        suitableSeasons: ["Kharif", "Rabi", "Zaid"],
        suitableSoils: ["Loamy", "Alluvial", "Black"],
        phRange: [5.5, 7.5],
        tempRange: [18, 35],
        rainfallRange: [500, 1000],
        irrigation: ["Rainfed", "Canal"],
        nitrogen: ["High"],
        phosphorus: ["High"],
        potassium: ["Medium"],
        budget: ["Low", "Medium"],
        cropType: "Cereal",
        states: ["Karnataka", "MP", "Maharashtra", "Bihar", "AP"],
        avgYield: "2.0 tonnes/acre",
        avgRevenue: 11000,
        riskLevel: "Moderate",
        waterRequirement: "Medium",
        growthDuration: "80–110 days",
        marketDemand: "High",
        mspSupport: true,
        pros: ["Versatile use", "Fast growing", "Industrial demand"],
        cons: ["Susceptible to Fall Armyworm", "Requires good drainage"],
        tips: "Use hybrid seeds for better yield. Control weeds in the first 45 days."
    },
    {
        name: "Cotton",
        localName: "Kapas",
        image_emoji: "☁️",
        suitableSeasons: ["Kharif"],
        suitableSoils: ["Black", "Alluvial"],
        phRange: [5.5, 8.5],
        tempRange: [21, 35],
        rainfallRange: [500, 1100],
        irrigation: ["Canal", "Borewell", "Drip"],
        nitrogen: ["High"],
        phosphorus: ["Medium"],
        potassium: ["High"],
        budget: ["High"],
        cropType: "Cash Crop",
        states: ["Gujarat", "Maharashtra", "Telangana", "Karnataka", "Punjab"],
        avgYield: "0.8 tonnes/acre",
        avgRevenue: 18000,
        riskLevel: "High",
        waterRequirement: "Medium",
        growthDuration: "150–180 days",
        marketDemand: "High",
        mspSupport: true,
        pros: ["High value cash crop", "Export potential"],
        cons: ["Pest sensitive (Bollworm)", "Long duration"],
        tips: "Opt for Bt Cotton varieties. Regular monitoring for sucking pests is vital."
    },
    {
        name: "Sugarcane",
        localName: "Ganna",
        image_emoji: "🎋",
        suitableSeasons: ["Kharif"],
        suitableSoils: ["Black", "Alluvial", "Loamy"],
        phRange: [6.5, 7.5],
        tempRange: [20, 45],
        rainfallRange: [1100, 1500],
        irrigation: ["Canal", "Drip", "Sprinkler"],
        nitrogen: ["High"],
        phosphorus: ["Medium"],
        potassium: ["High"],
        budget: ["High"],
        cropType: "Cash Crop",
        states: ["UP", "Maharashtra", "Karnataka", "Tamil Nadu", "Gujarat"],
        avgYield: "30 tonnes/acre",
        avgRevenue: 25000,
        riskLevel: "Low",
        waterRequirement: "Very High",
        growthDuration: "10–12 months",
        marketDemand: "High",
        mspSupport: true,
        pros: ["Assured returns", "Ratoon cropping possible"],
        cons: ["Extremely high water use", "Long maturity period"],
        tips: "Use wide-row planting for better sunlight and aeration. Switch to drip irrigation."
    },
    {
        name: "Soybean",
        localName: "Soyabean",
        image_emoji: "🫘",
        suitableSeasons: ["Kharif"],
        suitableSoils: ["Black", "Loamy"],
        phRange: [6.0, 7.5],
        tempRange: [20, 30],
        rainfallRange: [600, 1000],
        irrigation: ["Rainfed"],
        nitrogen: ["Low"],
        phosphorus: ["High"],
        potassium: ["Medium"],
        budget: ["Medium"],
        cropType: "Oilseed",
        states: ["MP", "Maharashtra", "Rajasthan", "Karnataka"],
        avgYield: "0.9 tonnes/acre",
        avgRevenue: 13500,
        riskLevel: "Moderate",
        waterRequirement: "Medium",
        growthDuration: "90–110 days",
        marketDemand: "High",
        mspSupport: true,
        pros: ["Nitrogen fixing", "Short duration", "High protein content"],
        cons: ["Sensitive to waterlogging", "Shattering loss"],
        tips: "Treat seeds with Rhizobium culture. Ensure field has no standing water."
    },
    {
        name: "Onion",
        localName: "Pyaj",
        image_emoji: "🧅",
        suitableSeasons: ["Kharif", "Rabi"],
        suitableSoils: ["Sandy", "Loamy", "Clay"],
        phRange: [6.0, 7.0],
        tempRange: [15, 30],
        rainfallRange: [650, 1000],
        irrigation: ["Sprinkler", "Drip", "Canal"],
        nitrogen: ["Medium"],
        phosphorus: ["High"],
        potassium: ["High"],
        budget: ["Medium"],
        cropType: "Vegetable",
        states: ["Maharashtra", "Karnataka", "Gujarat", "MP"],
        avgYield: "6 tonnes/acre",
        avgRevenue: 20000,
        riskLevel: "High",
        waterRequirement: "Medium",
        growthDuration: "120–150 days",
        marketDemand: "High",
        mspSupport: false,
        pros: ["Multiple harvests", "Good storage life"],
        cons: ["High price volatility", "Fungal disease risk"],
        tips: "Raise seedlings in nursery. Avoid excessive nitrogen during bulb development."
    },
    {
        name: "Tomato",
        localName: "Tamatar",
        image_emoji: "🍅",
        suitableSeasons: ["Kharif", "Rabi", "Zaid"],
        suitableSoils: ["Loamy", "Sandy", "Red & Laterite"],
        phRange: [6.0, 7.0],
        tempRange: [18, 28],
        rainfallRange: [600, 1500],
        irrigation: ["Drip", "Borewell"],
        nitrogen: ["Medium"],
        phosphorus: ["High"],
        potassium: ["High"],
        budget: ["High"],
        cropType: "Vegetable",
        states: ["Andhra Pradesh", "Karnataka", "MP", "Maharashtra", "Gujarat"],
        avgYield: "12 tonnes/acre",
        avgRevenue: 22000,
        riskLevel: "High",
        waterRequirement: "Medium",
        growthDuration: "100–120 days",
        marketDemand: "High",
        mspSupport: false,
        pros: ["High yield per acre", "Continuous income"],
        cons: ["Pest/Disease prone", "Perishable"],
        tips: "Use staking for better fruit quality. Mulching helps conserve moisture."
    },
    {
        name: "Potato",
        localName: "Aloo",
        image_emoji: "🥔",
        suitableSeasons: ["Rabi"],
        suitableSoils: ["Loamy", "Sandy"],
        phRange: [4.8, 6.0],
        tempRange: [15, 25],
        rainfallRange: [400, 600],
        irrigation: ["Sprinkler", "Canal"],
        nitrogen: ["High"],
        phosphorus: ["High"],
        potassium: ["High"],
        budget: ["High"],
        cropType: "Vegetable",
        states: ["UP", "West Bengal", "Bihar", "Gujarat", "MP"],
        avgYield: "10 tonnes/acre",
        avgRevenue: 15000,
        riskLevel: "Moderate",
        waterRequirement: "Medium",
        growthDuration: "90–120 days",
        marketDemand: "Very High",
        mspSupport: false,
        pros: ["High food value", "Good storage potential"],
        cons: ["Late blight disease", "Requires cold storage"],
        tips: "Ensure earthing up is done properly. Use disease-free seed tubers."
    },
    {
        name: "Chilli",
        localName: "Mirchi",
        image_emoji: "🌶️",
        suitableSeasons: ["Kharif", "Rabi"],
        suitableSoils: ["Black", "Loamy", "Red & Laterite"],
        phRange: [6.0, 7.0],
        tempRange: [20, 30],
        rainfallRange: [600, 1200],
        irrigation: ["Drip", "Borewell"],
        nitrogen: ["Medium"],
        phosphorus: ["High"],
        potassium: ["Medium"],
        budget: ["High"],
        cropType: "Spice",
        states: ["AP", "Telangana", "Karnataka", "MP", "Maharashtra"],
        avgYield: "1 tonne (Dry)/acre",
        avgRevenue: 35000,
        riskLevel: "High",
        waterRequirement: "Medium",
        growthDuration: "150–180 days",
        marketDemand: "High",
        mspSupport: false,
        pros: ["Excellent export value", "High price per unit"],
        cons: ["Leaf curl virus", "Labour intensive picking"],
        tips: "Control thrips and mites early. Use plastic mulch to control weeds."
    },
    {
        name: "Bajra (Pearl Millet)",
        localName: "Bajra",
        image_emoji: "🌾",
        suitableSeasons: ["Kharif"],
        suitableSoils: ["Sandy", "Arid & Desert"],
        phRange: [5.0, 8.0],
        tempRange: [25, 40],
        rainfallRange: [400, 750],
        irrigation: ["Rainfed"],
        nitrogen: ["Low"],
        phosphorus: ["Low"],
        potassium: ["Low"],
        budget: ["Low"],
        cropType: "Cereal",
        states: ["Rajasthan", "Maharashtra", "Gujarat", "UP", "Haryana"],
        avgYield: "0.8 tonnes/acre",
        avgRevenue: 8500,
        riskLevel: "Low",
        waterRequirement: "Low",
        growthDuration: "75–90 days",
        marketDemand: "Medium",
        mspSupport: true,
        pros: ["Drought tolerant", "Nutritious fodder"],
        cons: ["Lower market price", "Bird damage risk"],
        tips: "Ideal for dryland farming. Sowing should be done with first monsoon rain."
    },
    {
        name: "Jowar (Sorghum)",
        localName: "Jowar",
        image_emoji: "🎋",
        suitableSeasons: ["Kharif", "Rabi"],
        suitableSoils: ["Black", "Loamy", "Alluvial"],
        phRange: [6.0, 8.0],
        tempRange: [25, 32],
        rainfallRange: [400, 1000],
        irrigation: ["Rainfed", "Canal"],
        nitrogen: ["Medium"],
        phosphorus: ["Medium"],
        potassium: ["Low"],
        budget: ["Low"],
        cropType: "Cereal",
        states: ["Maharashtra", "Karnataka", "Rajasthan", "Tamil Nadu", "AP"],
        avgYield: "0.7 tonnes/acre",
        avgRevenue: 9000,
        riskLevel: "Low",
        waterRequirement: "Low",
        growthDuration: "100–115 days",
        marketDemand: "Medium",
        mspSupport: true,
        pros: ["Climate resilient", "Dual purpose (grain + fodder)"],
        cons: ["Stem borer pest", "Susceptible to grain mold in late rains"],
        tips: "Choose Maldandi variety for Rabi. Thinning is essential for good yield."
    },
    {
        name: "Tur Dal (Pigeon Pea)",
        localName: "Arhar",
        image_emoji: "🫘",
        suitableSeasons: ["Kharif"],
        suitableSoils: ["Black", "Loamy", "Red & Laterite"],
        phRange: [6.5, 7.5],
        tempRange: [20, 35],
        rainfallRange: [600, 1000],
        irrigation: ["Rainfed"],
        nitrogen: ["Low"],
        phosphorus: ["High"],
        potassium: ["Medium"],
        budget: ["Low"],
        cropType: "Pulse",
        states: ["Maharashtra", "Karnataka", "MP", "UP", "Gujarat"],
        avgYield: "0.6 tonnes/acre",
        avgRevenue: 15000,
        riskLevel: "Moderate",
        waterRequirement: "Medium",
        growthDuration: "160–200 days",
        marketDemand: "High",
        mspSupport: true,
        pros: ["Fixes atmospheric nitrogen", "High protein"],
        cons: ["Long duration", "Wilt disease risk"],
        tips: "Intercrop with Soybean or Maize for better risk management."
    },
    {
        name: "Gram (Chickpea)",
        localName: "Chana",
        image_emoji: "🫘",
        suitableSeasons: ["Rabi"],
        suitableSoils: ["Loamy", "Black"],
        phRange: [6.0, 9.0],
        tempRange: [15, 25],
        rainfallRange: [400, 700],
        irrigation: ["Rainfed", "Canal"],
        nitrogen: ["Low"],
        phosphorus: ["High"],
        potassium: ["Medium"],
        budget: ["Medium"],
        cropType: "Pulse",
        states: ["MP", "Maharashtra", "Rajasthan", "Karnataka", "UP"],
        avgYield: "0.7 tonnes/acre",
        avgRevenue: 14000,
        riskLevel: "Low",
        waterRequirement: "Low",
        growthDuration: "120–140 days",
        marketDemand: "High",
        mspSupport: true,
        pros: ["Low water need", "Improves soil fertility"],
        cons: ["Pod borer damage", "Sensitive to frost"],
        tips: "Treat seeds with Vitavax. One or two protective irrigations boost yield."
    },
    {
        name: "Groundnut",
        localName: "Mungfali",
        image_emoji: "🥜",
        suitableSeasons: ["Kharif", "Zaid"],
        suitableSoils: ["Sandy", "Loamy", "Red & Laterite"],
        phRange: [6.0, 7.5],
        tempRange: [20, 30],
        rainfallRange: [500, 1000],
        irrigation: ["Rainfed", "Sprinkler"],
        nitrogen: ["Low"],
        phosphorus: ["Medium"],
        potassium: ["Medium"],
        budget: ["Medium"],
        cropType: "Oilseed",
        states: ["Gujarat", "Rajasthan", "Tamil Nadu", "AP", "Karnataka"],
        avgYield: "1.2 tonnes/acre",
        avgRevenue: 16000,
        riskLevel: "Moderate",
        waterRequirement: "Medium",
        growthDuration: "100–120 days",
        marketDemand: "High",
        mspSupport: true,
        pros: ["Valuable oilseed", "Nitrogen fixer"],
        cons: ["Harvesting is difficult", "Aflatoxin risk in storage"],
        tips: "Gypsum application at flowering stage is crucial for pod development."
    },
    {
        name: "Mustard",
        localName: "Sarson",
        image_emoji: "🌼",
        suitableSeasons: ["Rabi"],
        suitableSoils: ["Alluvial", "Loamy", "Arid & Desert"],
        phRange: [6.0, 7.5],
        tempRange: [10, 25],
        rainfallRange: [400, 600],
        irrigation: ["Canal", "Borewell"],
        nitrogen: ["Medium"],
        phosphorus: ["High"],
        potassium: ["Medium"],
        budget: ["Low"],
        cropType: "Oilseed",
        states: ["Rajasthan", "Haryana", "MP", "UP", "Gujarat"],
        avgYield: "0.6 tonnes/acre",
        avgRevenue: 11000,
        riskLevel: "Low",
        waterRequirement: "Low",
        growthDuration: "110–130 days",
        marketDemand: "High",
        mspSupport: true,
        pros: ["Low input cost", "Short duration"],
        cons: ["Aphid attacks", "Seed shattering"],
        tips: "Spray Neem oil for aphids. Harvest when pods turn golden brown."
    },
    {
        name: "Sunflower",
        localName: "Surajmukhi",
        image_emoji: "🌻",
        suitableSeasons: ["Kharif", "Rabi", "Zaid"],
        suitableSoils: ["Black", "Alluvial", "Loamy"],
        phRange: [6.5, 8.0],
        tempRange: [20, 30],
        rainfallRange: [500, 800],
        irrigation: ["Sprinkler", "Canal"],
        nitrogen: ["Medium"],
        phosphorus: ["Medium"],
        potassium: ["High"],
        budget: ["Medium"],
        cropType: "Oilseed",
        states: ["Karnataka", "AP", "Maharashtra", "Bihar", "Haryana"],
        avgYield: "0.7 tonnes/acre",
        avgRevenue: 12000,
        riskLevel: "Moderate",
        waterRequirement: "Medium",
        growthDuration: "90–110 days",
        marketDemand: "Medium",
        mspSupport: true,
        pros: ["Drought tolerant", "Good for intercropping"],
        cons: ["Parrot damage", "Requires manual pollination sometimes"],
        tips: "Keep beehives near field for better pollination and yield."
    },
    {
        name: "Turmeric",
        localName: "Haldi",
        image_emoji: "🫚",
        suitableSeasons: ["Kharif"],
        suitableSoils: ["Red & Laterite", "Loamy", "Alluvial"],
        phRange: [5.5, 7.5],
        tempRange: [20, 35],
        rainfallRange: [1500, 2500],
        irrigation: ["Drip", "Borewell"],
        nitrogen: ["Medium"],
        phosphorus: ["Medium"],
        potassium: ["High"],
        budget: ["High"],
        cropType: "Spice",
        states: ["Telangana", "Maharashtra", "Tamil Nadu", "Karnataka", "AP"],
        avgYield: "8 tonnes (Fresh)/acre",
        avgRevenue: 40000,
        riskLevel: "Moderate",
        waterRequirement: "High",
        growthDuration: "7–9 months",
        marketDemand: "Very High",
        mspSupport: false,
        pros: ["High medicinal value", "Good storage life (dried)"],
        cons: ["Long duration", "Water intensive"],
        tips: "Use raised beds for planting. Mulch with green leaves to prevent moisture loss."
    },
    {
        name: "Ginger",
        localName: "Adrak",
        image_emoji: "🫚",
        suitableSeasons: ["Kharif"],
        suitableSoils: ["Loamy", "Red & Laterite", "Sandy"],
        phRange: [6.0, 7.0],
        tempRange: [20, 30],
        rainfallRange: [1500, 3000],
        irrigation: ["Rainfed", "Sprinkler"],
        nitrogen: ["Medium"],
        phosphorus: ["Medium"],
        potassium: ["High"],
        budget: ["High"],
        cropType: "Spice",
        states: ["Assam", "Kerala", "Karnataka", "Meghalaya", "Gujarat"],
        avgYield: "6 tonnes/acre",
        avgRevenue: 45000,
        riskLevel: "High",
        waterRequirement: "High",
        growthDuration: "8–9 months",
        marketDemand: "High",
        mspSupport: false,
        pros: ["Premium export crop", "Can be intercropped with trees"],
        cons: ["Rhizome rot disease", "Labour intensive"],
        tips: "Provide partial shade. Ensure very good drainage to avoid rotting."
    },
    {
        name: "Brinjal",
        localName: "Baingan",
        image_emoji: "🍆",
        suitableSeasons: ["Kharif", "Rabi", "Zaid"],
        suitableSoils: ["Loamy", "Black", "Alluvial"],
        phRange: [6.0, 7.5],
        tempRange: [20, 30],
        rainfallRange: [600, 1000],
        irrigation: ["Drip", "Canal"],
        nitrogen: ["High"],
        phosphorus: ["Medium"],
        potassium: ["Medium"],
        budget: ["Medium"],
        cropType: "Vegetable",
        states: ["West Bengal", "Orissa", "Gujarat", "Bihar", "Karnataka"],
        avgYield: "15 tonnes/acre",
        avgRevenue: 18000,
        riskLevel: "Moderate",
        waterRequirement: "Medium",
        growthDuration: "120–150 days",
        marketDemand: "High",
        mspSupport: false,
        pros: ["Long harvesting period", "Consistent demand"],
        cons: ["Shoot and fruit borer", "Bacterial wilt"],
        tips: "Use pheromone traps for borers. Regular picking encourages more fruiting."
    },
    {
        name: "Moong Dal",
        localName: "Moong",
        image_emoji: "🫘",
        suitableSeasons: ["Kharif", "Zaid"],
        suitableSoils: ["Loamy", "Alluvial"],
        phRange: [6.0, 7.5],
        tempRange: [25, 35],
        rainfallRange: [600, 900],
        irrigation: ["Rainfed", "Canal"],
        nitrogen: ["Low"],
        phosphorus: ["High"],
        potassium: ["Low"],
        budget: ["Low"],
        cropType: "Pulse",
        states: ["Rajasthan", "Maharashtra", "Karnataka", "MP", "AP"],
        avgYield: "0.4 tonnes/acre",
        avgRevenue: 12000,
        riskLevel: "Low",
        waterRequirement: "Low",
        growthDuration: "60–75 days",
        marketDemand: "High",
        mspSupport: true,
        pros: ["Very short duration", "Soil improver"],
        cons: ["Yellow Mosaic Virus", "Low yield per acre"],
        tips: "Ideal as a catch crop between two main seasons."
    },
    {
        name: "Barley",
        localName: "Jau",
        image_emoji: "🌾",
        suitableSeasons: ["Rabi"],
        suitableSoils: ["Sandy", "Loamy", "Alluvial"],
        phRange: [6.0, 8.5],
        tempRange: [10, 20],
        rainfallRange: [300, 500],
        irrigation: ["Canal", "Borewell"],
        nitrogen: ["Medium"],
        phosphorus: ["Medium"],
        potassium: ["Low"],
        budget: ["Low"],
        cropType: "Cereal",
        states: ["Rajasthan", "UP", "Haryana", "MP", "Punjab"],
        avgYield: "1.4 tonnes/acre",
        avgRevenue: 10000,
        riskLevel: "Low",
        waterRequirement: "Low",
        growthDuration: "100–120 days",
        marketDemand: "Medium",
        mspSupport: true,
        pros: ["Salt tolerant", "Requires less water than wheat"],
        cons: ["Lower price than wheat", "Industrial demand is specific"],
        tips: "Often grown on marginal lands. Avoid excessive irrigation."
    },
    {
        name: "Sunflower",
        localName: "Surajmukhi",
        image_emoji: "🌻",
        suitableSeasons: ["Kharif", "Rabi", "Zaid"],
        suitableSoils: ["Black", "Alluvial", "Loamy"],
        phRange: [6.5, 8.0],
        tempRange: [20, 30],
        rainfallRange: [500, 800],
        irrigation: ["Sprinkler", "Canal"],
        nitrogen: ["Medium"],
        phosphorus: ["Medium"],
        potassium: ["High"],
        budget: ["Medium"],
        cropType: "Oilseed",
        states: ["Karnataka", "AP", "Maharashtra", "Bihar", "Haryana"],
        avgYield: "0.7 tonnes/acre",
        avgRevenue: 12000,
        riskLevel: "Moderate",
        waterRequirement: "Medium",
        growthDuration: "90–110 days",
        marketDemand: "Medium",
        mspSupport: true,
        pros: ["Drought tolerant", "Good for intercropping"],
        cons: ["Parrot damage", "Requires manual pollination sometimes"],
        tips: "Keep beehives near field for better pollination and yield."
    },
    {
        name: "Linseed",
        localName: "Alsi",
        image_emoji: "🌱",
        suitableSeasons: ["Rabi"],
        suitableSoils: ["Black", "Alluvial", "Loamy"],
        phRange: [6.0, 7.5],
        tempRange: [10, 25],
        rainfallRange: [400, 600],
        irrigation: ["Canal", "Borewell"],
        nitrogen: ["Low"],
        phosphorus: ["Medium"],
        potassium: ["Low"],
        budget: ["Low"],
        cropType: "Oilseed",
        states: ["MP", "UP", "Maharashtra", "Bihar", "Chhattisgarh"],
        avgYield: "0.5 tonnes/acre",
        avgRevenue: 9000,
        riskLevel: "Low",
        waterRequirement: "Low",
        growthDuration: "120–140 days",
        marketDemand: "Medium",
        mspSupport: false,
        pros: ["Valuable oil and fiber", "Grown with limited irrigation"],
        cons: ["Sensitive to weed competition", "Rust disease"],
        tips: "Sow in lines for better weed control. Apply 1–2 irrigations at critical stages."
    },
    {
        name: "Jute",
        localName: "Patsan",
        image_emoji: "🌱",
        suitableSeasons: ["Kharif"],
        suitableSoils: ["Alluvial", "Loamy"],
        phRange: [6.0, 7.5],
        tempRange: [24, 35],
        rainfallRange: [1500, 2500],
        irrigation: ["Rainfed", "Canal"],
        nitrogen: ["High"],
        phosphorus: ["Medium"],
        potassium: ["Medium"],
        budget: ["Medium"],
        cropType: "Cash Crop",
        states: ["West Bengal", "Bihar", "Assam", "Orissa", "AP"],
        avgYield: "1.2 tonnes (Fiber)/acre",
        avgRevenue: 16000,
        riskLevel: "Moderate",
        waterRequirement: "High",
        growthDuration: "120–150 days",
        marketDemand: "High",
        mspSupport: true,
        pros: ["Eco-friendly fiber", "Good returns in Eastern India"],
        cons: ["Requires lot of water for retting", "Labour intensive"],
        tips: "Retting should be done in clean, slow-flowing water for high-quality fiber."
    }
];

const priceData = [
    { name: "Rice", price: 2183, msp: 2183, change: "+0.0%", demand: "High", trend: "neutral" },
    { name: "Wheat", price: 2275, msp: 2275, change: "+1.2%", demand: "High", trend: "up" },
    { name: "Maize", price: 1850, msp: 1870, change: "-0.8%", demand: "Medium", trend: "down" },
    { name: "Tur Dal", price: 6800, msp: 6600, change: "+3.1%", demand: "High", trend: "up" },
    { name: "Gram", price: 5440, msp: 5440, change: "+0.0%", demand: "High", trend: "neutral" },
    { name: "Groundnut", price: 5850, msp: 5850, change: "+0.5%", demand: "Medium", trend: "up" },
    { name: "Mustard", price: 5650, msp: 5650, change: "-1.2%", demand: "Medium", trend: "down" },
    { name: "Cotton", price: 6620, msp: 6620, change: "+2.0%", demand: "High", trend: "up" },
    { name: "Sugarcane", price: 315, msp: 315, change: "+0.0%", demand: "Medium", trend: "neutral" },
    { name: "Soybean", price: 4600, msp: 4600, change: "-0.3%", demand: "Medium", trend: "down" },
    { name: "Tomato", price: 1200, msp: "N/A", change: "+15%", demand: "High", trend: "up" },
    { name: "Onion", price: 800, msp: "N/A", change: "-5%", demand: "Medium", trend: "down" },
    { name: "Potato", price: 1100, msp: "N/A", change: "+2%", demand: "High", trend: "up" },
    { name: "Chilli", price: 12000, msp: "N/A", change: "+8%", demand: "High", trend: "up" },
    { name: "Turmeric", price: 14500, msp: "N/A", change: "+12%", demand: "High", trend: "up" }
];

const weatherMock = {
    city: "Pune, Maharashtra",
    temperature: 28,
    feelsLike: 31,
    humidity: 65,
    windSpeed: 12,
    windDir: "NE",
    condition: "Partly Cloudy",
    visibility: 8,
    uvIndex: 6,
    rainfall: 8,
    forecast: [
        { day: "Mon", high: 30, low: 22, condition: "Sunny" },
        { day: "Tue", high: 29, low: 21, condition: "Cloudy" },
        { day: "Wed", high: 27, low: 20, condition: "Rain" },
        { day: "Thu", high: 26, low: 19, condition: "Rain" },
        { day: "Fri", high: 28, low: 21, condition: "Partly Cloudy" }
    ]
};

const stateData = {
    "Maharashtra": { soil: "Black", climate: "Semi-arid", rainfall: "700–1200mm" },
    "Punjab": { soil: "Alluvial", climate: "Sub-humid", rainfall: "500–800mm" },
    "Karnataka": { soil: "Red & Laterite", climate: "Semi-arid", rainfall: "600–1200mm" },
    "Uttar Pradesh": { soil: "Alluvial", climate: "Sub-humid", rainfall: "700–1000mm" },
    "Rajasthan": { soil: "Arid & Desert", climate: "Arid", rainfall: "200–400mm" },
    "Madhya Pradesh": { soil: "Black", climate: "Sub-humid", rainfall: "700–1200mm" },
    "Tamil Nadu": { soil: "Red & Laterite", climate: "Tropical", rainfall: "900–1200mm" },
    "Gujarat": { soil: "Black", climate: "Arid-Semi-arid", rainfall: "400–900mm" },
    "Bihar": { soil: "Alluvial", climate: "Humid subtropical", rainfall: "1000–1500mm" },
    "Andhra Pradesh": { soil: "Red & Laterite", climate: "Tropical", rainfall: "900–1100mm" }
};
